name = "YOUR_HOSTNAME_HERE"
host = "0.0.0.0"
port = 7788
players = 1024
password = "YOUR_PASSWORD_HERE"
announce = false
gamemode = "0.1.0-beta"
language = "en"
description = "YOUR_DESCRIPTION_HERE"
debug = true
modules = [
  "js-module"
]
resources = ["YOUR_RESOURCE_HERE"]
tags = []